### ISSUE TITLE
how to generate SCHEMA_ID_UDA

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lib#39]
Hi there, I want to generate a SCHEMA_ID_UDA, I found SCHEMA_ID_CFA in wallet/mod.rs, but I don't know how to get a related string, so come here for help:)
pub(crate) const SCHEMA_ID_NIA: &str =
    "urn:lnp-bp:sc:BEiLYE-am9WhTW1-oK8cpvw4-FEMtzMrf-mKocuGZn-qWK6YF#ginger-parking-nirvana";
pub(crate) const SCHEMA_ID_CFA: &str =
    "urn:lnp-bp:sc:4nfgJ2-jkeTRQuG-uTet6NSW-Fy1sFTU8-qqrN2uY2-j6S5rv#ravioli-justin-brave";

**Comment by zoedberg** [comment]
Hi! In order to generate schema IDs you can do:

```rust
use rgb_schemata::{cfa_schema, nia_schema, uda_schema};

println!("NIA schema ID: {}", nia_schema().schema_id());
println!("CFA schema ID: {}", cfa_schema().schema_id());
println!("UDA schema ID: {}", uda_schema().schema_id());
```

Not sure why you're asking this in the rgb-lib repository though. If you are trying to add UDA support you should know that we're already working on it and we almost completed the task.

**Comment by zoedberg** [comment]
1. We'll complete the task in a week or so. It will not be producion-ready though since we still need to wait for RGB v0.11, an intesive testing phase and an auditing before being confident that it can be considered safe for production use
2. For sure we'll add UDA on-chain support. Maybe in the future we'll support it also for opening channels but currently we don't see this as a priority
3. We have some new features in mind, but we don't have a specific roadmap to commit to
