### ISSUE TITLE
Remove max fee rate limit

### ISSUE THREAD

**Issue by cakesoft-shashank** [RGB-Tools/rgb-lib#50]
1. The library currently restricts the fee rate to a maximum of 1000 sats/vB, throwing an InvalidFeeRate exception with the message "value above maximum 1000". As per current congestion on testnet, we're unable to create UTXOs when minimum fees exceed 1000 sats/vB. 
<img width="568" alt="Screenshot 2024-10-25 at 11 12 51 AM" src="https://github.com/user-attachments/assets/e7323469-03d6-429c-bf40-93f7b70e0715">

2. For testing purposes, is it possible to allow UTXO creation without a priority fee. This would allow for more flexible testing without any fee constraints.

**Comment by zoedberg** [comment]
1. We'll remove the upper bound limit since it was there only to prevent users to spend too much in fees, but this check could be done directly by the user interface. Thanks for reporting this.
2. Unfortunately this is not possible, when creating a TX providing a fee rate is mandatory and we cannot find a default value that would work in every case

**Comment by zoedberg** [comment]
Done in https://github.com/RGB-Tools/rgb-lib/pull/52/commits/bc0f633e91ebdf0340b4d07c713146110d1a8e04. I'll close this issue once we'll do a release with this fix included

**Comment by zoedberg** [comment]
Closing this since we released 0.3.0-alpha.11
